version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.7
  github: haskell-works/github-release@1.3.3
  hackage: haskell-works/hackage@1.4.1
  merge-point: haskell-works/merge-point@1.0.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.8.3
          executor: haskell/ghc-8_8_3
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.10.1
          executor: haskell/ghc-8_10_1
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - merge-point/merge-point:
          name: Build Ok
          requires:
            - GHC 8.4.4
            - GHC 8.6.5
            - GHC 8.8.3
            - GHC 8.10.1

      - github/release-cabal:
          name: GitHub Release
          context: haskell-ci
          requires:
            - Build Ok
          checkout: true
          filters:
            branches:
              only: master

      - hackage/upload:
          context: haskell-ci
          publish: true
          requires:
            - GitHub Release
          username: ${HACKAGE_USER}
          password: ${HACKAGE_PASS}
