version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.0.5
  github: haskell-works/github-release@1.2.1
  hackage: haskell-works/hackage@1.3.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.2.2
          executor: haskell/ghc-8_2_2
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - haskell/build-with-binary-cache:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - haskell/build-with-binary-cache:
          name: GHC 8.8.2
          executor: haskell/ghc-8_8_2
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - github/release-cabal:
          name: GitHub Release
          context: haskell-ci
          requires:
            - GHC 8.2.2
            - GHC 8.4.4
            - GHC 8.6.5
            - GHC 8.8.2
          checkout: true
          filters:
            branches:
              only: master

      - hackage/upload:
          context: haskell-ci
          publish: true
          requires:
            - GitHub Release
          username: ${HACKAGE_USER}
          password: ${HACKAGE_PASS}
